channels:
- conda-forge
dependencies:
- python=3.12.14
- pip<=26.2.1
- pip:
  - mlflow==3.16.0
  - numpy==2.4.6
  - pandas==2.3.3
  - scikit-learn==1.9.1
  - lightgbm==4.7.0
  - tensorflow==2.21.0
  - keras==3.15.1
  - cloudpickle==3.1.2
name: mlflow-env
