/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ps3/subsystems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Subsystems */
        get: operations["subsystems_api_ps3_subsystems_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ps3/subsystems/{subsystem}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Subsystem */
        get: operations["subsystem_api_ps3_subsystems__subsystem__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ps3/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_api_ps3_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ps3/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_ps3_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ps3/runs/{run_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload
         * @description Check one uploaded file, run the subsystem's model on it, and add it to the run.
         */
        post: operations["upload_api_ps3_runs__run_id__files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ps3/runs/{run_id}/{csv_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Csv */
        get: operations["download_csv_api_ps3_runs__run_id___csv_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ps3/submission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Submission */
        get: operations["get_submission_api_ps3_submission_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ps3/submission/predictions.zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Zip */
        get: operations["download_zip_api_ps3_submission_predictions_zip_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcvCar */
        AcvCar: {
            /** Car */
            car: string;
            /** Parameters */
            parameters: number;
            /** Coolingshare */
            coolingShare: number | null;
            /** Indoormean */
            indoorMean: number | null;
            /** Gapwhilecooling */
            gapWhileCooling: number | null;
            /** Indoor */
            indoor: (number | null)[];
            /** Setpoint */
            setpoint: (number | null)[];
        };
        /** AcvView */
        AcvView: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "acv";
            /** Rows */
            rows: number;
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
            /** Sampleperiods */
            samplePeriodS: number | null;
            /** Trainnumber */
            trainNumber: string | null;
            /** Time */
            time: string[];
            /** Cars */
            cars: components["schemas"]["AcvCar"][];
            /** Rankedcars */
            rankedCars: string[] | null;
        };
        /** Body_upload_api_ps3_runs__run_id__files_post */
        Body_upload_api_ps3_runs__run_id__files_post: {
            /** File */
            file: string;
        };
        /** Check */
        Check: {
            /** Label */
            label: string;
            /**
             * State
             * @enum {string}
             */
            state: "pass" | "warn" | "fail";
            /** Detail */
            detail?: string | null;
        };
        /** DoorCycle */
        DoorCycle: {
            /** Index */
            index: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Startnative */
            startNative: string;
            /** Endnative */
            endNative: string;
            /** Durations */
            durationS: number;
            /**
             * Operation
             * @enum {string}
             */
            operation: "Open" | "Close";
            /** Prediction */
            prediction: ("Normal" | "Abnormal resistance") | null;
            /** Windowcurrent */
            windowCurrent: number | null;
            /** Threshold */
            threshold: number | null;
            /** Current */
            current: number[];
            /** Position */
            position: number[];
            /** Profile */
            profile: number[];
        };
        /** DoorReference */
        DoorReference: {
            /**
             * Operation
             * @enum {string}
             */
            operation: "Open" | "Close";
            /**
             * Status
             * @enum {string}
             */
            status: "Normal" | "Abnormal resistance";
            /** Profile */
            profile: number[];
        };
        /** DoorView */
        DoorView: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "door";
            /** Rows */
            rows: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Sampleperiodms */
            samplePeriodMs: number;
            /** Cycles */
            cycles: components["schemas"]["DoorCycle"][];
            /** Windows */
            windows: {
                [key: string]: number[];
            };
            /** References */
            references: components["schemas"]["DoorReference"][];
        };
        /** FileResult */
        FileResult: {
            /** Filename */
            fileName: string;
            /** Sizebytes */
            sizeBytes: number;
            /** Ok */
            ok: boolean;
            /** Lookslike */
            looksLike: ("door" | "acv" | "rail" | "shm") | null;
            /** Checks */
            checks: components["schemas"]["Check"][];
            /** Prediction */
            prediction: string | null;
            /** Rows */
            rows: number;
            /** View */
            view: (components["schemas"]["DoorView"] | components["schemas"]["AcvView"] | components["schemas"]["RailView"] | components["schemas"]["ShmView"]) | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** ModelCard */
        ModelCard: {
            /** Name */
            name: string;
            /** Version */
            version: string;
            /** Method */
            method: string;
            /** Trainedon */
            trainedOn: string;
            /** Validation */
            validation: string;
            /** Parameters */
            parameters: {
                [key: string]: number;
            };
        };
        /** NewRun */
        NewRun: {
            /**
             * Subsystem
             * @enum {string}
             */
            subsystem: "door" | "acv" | "rail" | "shm";
        };
        /** RailChannel */
        RailChannel: {
            /** Car */
            car: number;
            /** Position */
            position: number;
            /**
             * Side
             * @enum {string}
             */
            side: "Side I" | "Side II";
            /** Vibration */
            vibration: number;
            /** Shock */
            shock: number;
        };
        /** RailView */
        RailView: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "rail";
            /** Rows */
            rows: number;
            /** Durations */
            durationS: number;
            /** Speedkmh */
            speedKmh: number;
            /** Channels */
            channels: components["schemas"]["RailChannel"][];
            /** Sidevibration */
            sideVibration: {
                [key: string]: number;
            };
            /** Sideshock */
            sideShock: {
                [key: string]: number;
            };
        };
        /** Run */
        Run: {
            /** Id */
            id: string;
            /**
             * Subsystem
             * @enum {string}
             */
            subsystem: "door" | "acv" | "rail" | "shm";
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Status
             * @enum {string}
             */
            status: "empty" | "ready" | "pending" | "invalid";
            /** Files */
            files: number;
            /** Validfiles */
            validFiles: number;
            /** Rows */
            rows: number;
            /** Summary */
            summary: string;
            /** Csvname */
            csvName: string;
            /** Csvurl */
            csvUrl: string | null;
            /** Results */
            results: components["schemas"]["FileResult"][];
        };
        /** RunSummary */
        RunSummary: {
            /** Id */
            id: string;
            /**
             * Subsystem
             * @enum {string}
             */
            subsystem: "door" | "acv" | "rail" | "shm";
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Status
             * @enum {string}
             */
            status: "empty" | "ready" | "pending" | "invalid";
            /** Files */
            files: number;
            /** Validfiles */
            validFiles: number;
            /** Rows */
            rows: number;
            /** Summary */
            summary: string;
            /** Csvname */
            csvName: string;
            /** Csvurl */
            csvUrl: string | null;
        };
        /** ShmView */
        ShmView: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "shm";
            /** Samples */
            samples: number;
            /** Minimum */
            minimum: number;
            /** Maximum */
            maximum: number;
            /** Mean */
            mean: number;
            /** Std */
            std: number;
            /** Envelopemin */
            envelopeMin: number[];
            /** Envelopemax */
            envelopeMax: number[];
        };
        /** Submission */
        Submission: {
            /** Zipname */
            zipName: string;
            /** Ready */
            ready: number;
            /** Items */
            items: components["schemas"]["SubmissionItem"][];
            /** Zipurl */
            zipUrl: string | null;
        };
        /** SubmissionItem */
        SubmissionItem: {
            /**
             * Subsystem
             * @enum {string}
             */
            subsystem: "door" | "acv" | "rail" | "shm";
            /** Name */
            name: string;
            /** Outputfile */
            outputFile: string;
            /** Status */
            status: ("empty" | "ready" | "pending" | "invalid") | "none";
            run: components["schemas"]["RunSummary"] | null;
            /** Included */
            included: boolean;
            /** Note */
            note: string;
        };
        /** SubsystemInfo */
        SubsystemInfo: {
            /**
             * Id
             * @enum {string}
             */
            id: "door" | "acv" | "rail" | "shm";
            /** Name */
            name: string;
            /** Question */
            question: string;
            /** Task */
            task: string;
            /** Inputhint */
            inputHint: string;
            /** Accepts */
            accepts: string[];
            /** Multiple */
            multiple: boolean;
            /** Outputfile */
            outputFile: string;
            /** Outputcolumns */
            outputColumns: string[];
            /** Labels */
            labels: string[];
            /** Metric */
            metric: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "pending";
            /** Statusnote */
            statusNote: string;
            model: components["schemas"]["ModelCard"] | null;
            latestRun: components["schemas"]["RunSummary"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    subsystems_api_ps3_subsystems_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubsystemInfo"][];
                };
            };
        };
    };
    subsystem_api_ps3_subsystems__subsystem__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subsystem: "door" | "acv" | "rail" | "shm";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubsystemInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_ps3_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewRun"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_ps3_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_api_ps3_runs__run_id__files_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_api_ps3_runs__run_id__files_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_csv_api_ps3_runs__run_id___csv_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                csv_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_submission_api_ps3_submission_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"];
                };
            };
        };
    };
    download_zip_api_ps3_submission_predictions_zip_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": unknown;
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
